### ISSUE TITLE
tutor-forum upgrade to Ruby 3.3

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor-forum#33]
From https://discuss.openedx.org/t/tutor-cs-comment-service-mongo-and-ruby-upgrade/12472 :

> We just tested and landed [this change 3](https://github.com/openedx/cs_comments_service/pull/426) which has confirmed that the latest version of cs_comment_service will work with Ruby 3.3 and Mongo 7.
> I don’t know what is involved but the relevant tutor code and images should be updated.
> If this is using the same Mongo instance as the LMS/CMS, then maybe hold off on the mongo upgrade there until [chore: add mongo 7 to testing matrix by DanielVZ96 · Pull Request #34213 · openedx/edx-platform · GitHub 1](https://github.com/openedx/edx-platform/pull/34213) merges which will hopefully be soon!

**Comment by kdmccormick** [comment]
@ghassanmas , will you be able to apply and test the Ruby 3.3 upgrade?

**Comment by ghassanmas** [comment]
@kdmccormick yes will do, hopefuly in frinday by the end of this week.

**Comment by ghassanmas** [comment]
@kdmccormick looking now again at it, I can start with Ruby 3.3, but it would use old mongo verison, given tutor nightly still not updated to mongo 7, so if I understnad correcly I shall wait until tutor nightly is using mongo 7 (https://github.com/overhangio/tutor/issues/1020 ) ? is that correct?. Otherwise I would be testing Ruby 3.3 with Mongo `4.4.25` https://github.com/overhangio/tutor/blob/404332b80142ac86ed612cc41b7c953adbc8f75f/tutor/templates/config/defaults.yml#L23

**Comment by kdmccormick** [comment]
Good point @ghassanmas , it would fair for you to wait until Tutor upgrades to Mongo 7 first.

**Comment by DawoudSheraz** [comment]
@ghassanmas Hi, the mongo PR has been merged to nightly. You are all set for this. Thanks

**Comment by ghassanmas** [comment]
I am not sure which Gemfile or Gemfile.lock, it's suppsoe to be used for 3.3. 
Earlier we had Gemfile and Gemfile3 where the former for Ruby 2.* and the latter for ruby 3.*. 

However now I can see Gemfile is pinned for ruby 3.1, while Gemfile3 for 3.0. So I  though given 3.3. is cloaser to 3.1, Gemfile is suppose to be used, but it didn't work because it's missing a library, thus I openedx a PR upstream to add it 
- https://github.com/openedx/cs_comments_service/pull/429
